# See https://pre-commit.com for more information

# See https://pre-commit.ci/ for information about the continuous
# integration service for the pre-commit framework 
ci:
    autofix_prs: false
    autoupdate_schedule: weekly
    autoupdate_commit_msg: 'chore(deps): pre-commit autoupdate'


# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
    -   id: pyupgrade
        name: pyupgrade (python)
        args: [--py37-plus]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: black (python)
